import axios from 'axios';
import { supabase } from '../utils/supabaseClient.js';

const SQUADCO_API_KEY = process.env.SQUADCO_API_KEY;
const SQUADCO_API_URL = process.env.SQUADCO_API_URL || 'https://api-d.squadco.com';

/**
 * Initialize payment with Squad API
 * @param {number} amountInNaira - Amount in Naira (will be converted to kobo)
 * @param {string} email - Customer email
 * @param {string} callbackUrl - Callback URL for payment confirmation
 * @param {string} transactionRef - Transaction reference (generated by controller, NOT here)
 * @returns {Promise<Object>} - Squad API response with payment link
 */
export const initiateSquadPayment = async (amountInNaira, email, callbackUrl, transactionRef) => {
  try {
    // Validate inputs
    if (!amountInNaira || amountInNaira <= 0) {
      throw new Error('Invalid amount: must be greater than 0');
    }
    if (!email || !email.includes('@')) {
      throw new Error('Invalid email address');
    }
    if (!callbackUrl) {
      throw new Error('Callback URL is required');
    }
    if (!transactionRef) {
      throw new Error('Transaction reference is required');
    }
    if (!SQUADCO_API_KEY) {
      throw new Error('SQUADCO_API_KEY not configured in environment variables');
    }

    // 🔑 CRITICAL: Use the reference passed from controller, do NOT generate a new one
    console.log('🔑 USING REFERENCE FROM CONTROLLER:', transactionRef);

    // Convert Naira to Kobo (1 Naira = 100 Kobo)
    const amountInKobo = Math.round(amountInNaira * 100);

    // Build request payload
    const requestPayload = {
      amount: amountInKobo,
      email,
      currency: 'NGN',
      initiate_type: 'inline',
      transaction_ref: transactionRef,
      callback_url: callbackUrl,
    };

    console.log('📤 Squad Payment Initiation Request:', {
      url: `${SQUADCO_API_URL}/transaction/initiate`,
      amountInNaira,
      amountInKobo,
      email,
      transactionRef,
      timestamp: new Date().toISOString(),
    });

    // Make API request to Squad
    const response = await axios.post(
      `${SQUADCO_API_URL}/transaction/initiate`,
      requestPayload,
      {
        headers: {
          Authorization: `Bearer ${SQUADCO_API_KEY}`,
          'Content-Type': 'application/json',
        },
        timeout: 30000, // 30 second timeout (increased from 10000)
      }
    );

    console.log('✅ Squad Payment Response:', {
      status: response.status,
      success: response.data?.success,
      hasCheckoutUrl: !!response.data?.data?.checkout_url,
      timestamp: new Date().toISOString(),
    });

    // Validate response
    if (!response.data || !response.data.success) {
      throw new Error(`Squad API error: ${response.data?.message || 'Unknown error'}`);
    }

    if (!response.data.data || !response.data.data.checkout_url) {
      throw new Error('Squad API did not return checkout URL');
    }

    // Return success response
    return {
      success: true,
      checkoutUrl: response.data.data.checkout_url,
      transactionRef: response.data.data.transaction_ref || transactionRef,
      amount: amountInKobo,
      amountInNaira,
      email,
      message: 'Payment initialized successfully',
    };
  } catch (error) {
    console.error('❌ Squad Payment Initiation Error:', {
      message: error.message,
      status: error.response?.status,
      statusText: error.response?.statusText,
      data: error.response?.data,
      timestamp: new Date().toISOString(),
    });

    return {
      success: false,
      error: error.message || 'Failed to initiate payment',
      details: error.response?.data || null,
    };
  }
};

/**
 * Verify payment with Squad API
 * @param {string} transactionRef - Transaction reference to verify
 * @returns {Promise<Object>} - Payment verification result
 */
export const verifySquadPayment = async (transactionRef) => {
  try {
    if (!transactionRef) {
      throw new Error('Transaction reference is required');
    }
    if (!SQUADCO_API_KEY) {
      throw new Error('SQUADCO_API_KEY not configured');
    }

    console.log('📤 Squad Payment Verification Request:', {
      url: `${SQUADCO_API_URL}/transaction/verify/${transactionRef}`,
      transactionRef,
      timestamp: new Date().toISOString(),
    });

    const response = await axios.get(
      `${SQUADCO_API_URL}/transaction/verify/${transactionRef}`,
      {
        headers: {
          Authorization: `Bearer ${SQUADCO_API_KEY}`,
          'Content-Type': 'application/json',
        },
        timeout: 30000, // 30 second timeout (increased from 10000)
      }
    );

    console.log('✅ Squad Payment Verification Response:', {
      status: response.status,
      paymentStatus: response.data?.data?.status,
      timestamp: new Date().toISOString(),
      fullResponse: JSON.stringify(response.data, null, 2),
    });

    if (!response.data || !response.data.data) {
      throw new Error('Invalid response from Squad API');
    }

    const paymentData = response.data.data;

    // CRITICAL: Check both possible status field names
    const paymentStatus = paymentData.transaction_status || paymentData.status;

    // Only mark as success if status is truly 'success'
    if (paymentStatus !== 'success') {
      console.warn('⚠️ Payment not successful:', {
        status: paymentStatus,
        reference: paymentData.transaction_ref || transactionRef,
      });
      
      return {
        success: false,
        error: `Payment status: ${paymentStatus}`,
        status: paymentStatus,
        reference: paymentData.transaction_ref || transactionRef,
        amount: paymentData.amount,
        rawData: paymentData,
      };
    }

    // Amount is in kobo, convert to Naira for comparison
    const amountInNaira = Math.round(paymentData.amount / 100);

    return {
      success: true,
      status: paymentStatus,
      reference: paymentData.transaction_ref || transactionRef,
      amount: amountInNaira, // Return in Naira
      amountInKobo: paymentData.amount, // Also return raw kobo for reference
      email: paymentData.customer_email,
      message: 'Payment verified successfully',
      rawData: paymentData,
    };
  } catch (error) {
    console.error('❌ Squad Payment Verification Error:', {
      message: error.message,
      status: error.response?.status,
      data: error.response?.data,
      timestamp: new Date().toISOString(),
    });

    return {
      success: false,
      error: error.message || 'Failed to verify payment',
      details: error.response?.data || null,
    };
  }
};
